Importing Libraries

In [15]:
import numpy as np
import pandas as pd
from datetime import datetime
import re

Loading Dataset

In [16]:
df = pd.read_csv('anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

Extract Anime Type

In [17]:
def extract_type(title):
    if 'Movie' in title:
        return 'Movie'
    elif 'OVA' in title:
        return 'OVA'
    elif 'Special' in title:
        return 'Special'
    else:
        return 'TV'
    
df['Type'] = df['Title'].apply(extract_type)
df.head()

   Rank                                              Title  Score Type
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   TV
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   TV
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   TV
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   TV
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   TV

Extracing Episodes

In [22]:
def extract_episodes(title):
    match = re.search(r'\((\d+)', title)
    return int(match.group(1)) if match else np.nan

df['Episodes'] = df['Title'].apply(extract_episodes)
df.head()

,Rank,Title,Score,Type,Episodes,Release Year
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,TV,64,2009
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,TV,24,2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,TV,13,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,TV,51,2015
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,TV,10,2019

Extracting Release Year

In [21]:
def extract_year(title):
    match = re.search(r'(19|20)(\d{2})', title)
    return int(match.group()) if match else np.nan

df['Release Year'] = df['Title'].apply(extract_year)
df.head()

,Rank,Title,Score,Type,Episodes,Release Year
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,TV,64,2009
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,TV,24,2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,TV,13,2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,TV,51,2015
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,TV,10,2019

Creating Anime Length Feature (Short/Long)

In [26]:
df['Length Type'] = df['Episodes'].apply(
    lambda x: 'Long' if x >= 50 else 'Short'
)

df.head()

,Rank,Title,Score,Type,Episodes,Release Year,Length_Type,Length Type
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,TV,64,2009,Long,Long
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,TV,24,2011,Short,Short
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,TV,13,2022,Short,Short
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,TV,51,2015,Long,Long
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,TV,10,2019,Short,Short

Creating Top Tier Feature

In [30]:
df['Top Tier'] = df['Score'].apply(
    lambda x: 'Yes' if x >= 8.5 else 'No'
)

df.head()

,Rank,Title,Score,Type,Episodes,Release Year,Length Type,Top Tier
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,TV,64,2009,Long,Yes
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,TV,24,2011,Short,Yes
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,TV,13,2022,Short,Yes
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,TV,51,2015,Long,Yes
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,TV,10,2019,Short,Yes

Creating Anime Age Feature

In [32]:
current_year = datetime.now().year
df['Anime Age'] = current_year - df['Release Year']
df.head()

,Rank,Title,Score,Type,Episodes,Release Year,Length Type,Top Tier,Anime Age
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,TV,64,2009,Long,Yes,17
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,TV,24,2011,Short,Yes,15
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,TV,13,2022,Short,Yes,4
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,TV,51,2015,Long,Yes,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,TV,10,2019,Short,Yes,7