In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['CS', 'IT', 'CS', 'IT', 'SE'],
    'Student': ['Ali', 'Sara', 'Ahmed', 'Usman', 'Ahsan'],
    'CGPA': [3.5, 3.8, 3.2, 3.9, 3.6],
    'Age': [21, 22, 20, 23, 21]
})

In [3]:
df

  Department Student  CGPA  Age
0         CS     Ali   3.5   21
1         IT    Sara   3.8   22
2         CS   Ahmed   3.2   20
3         IT   Usman   3.9   23
4         SE   Ahsan   3.6   21

Average CGPA per Department

In [4]:
df.groupby('Department')['CGPA'].mean()

Department
CS    3.35
IT    3.85
SE    3.60
Name: CGPA, dtype: float64

Sum of CGPA of per Department

In [5]:
df.groupby('Department')['CGPA'].sum()

Department
CS    6.7
IT    7.7
SE    3.6
Name: CGPA, dtype: float64

GroupBy + Multiple Aggregations

In [6]:
df.groupby('Department')['CGPA'].agg(['mean', 'max', 'min'])

            mean  max  min
Department
CS          3.35  3.5  3.2
IT          3.85  3.9  3.8
SE          3.60  3.6  3.6

GroupBy + Multiple Columns + Multiple Aggregations

In [7]:
df.groupby('Department').agg({
    'CGPA': ['mean', 'max'],
    'Age': 'mean'
})

            CGPA        Age
            mean  max  mean
Department
CS          3.35  3.5  20.5
IT          3.85  3.9  22.5
SE          3.60  3.6  21.0

Rename Aggregated Columns

In [8]:
df.groupby('Department').agg(
    Avg_CGPA = ('CGPA', 'mean'),
    Max_CGPA = ('CGPA', 'max'),
    Min_CGPA = ('CGPA',  'min'),
    Avg_Age = ('Age', 'mean')
)

            Avg_CGPA  Max_CGPA  Min_CGPA  Avg_Age
Department
CS              3.35       3.5       3.2     20.5
IT              3.85       3.9       3.8     22.5
SE              3.60       3.6       3.6     21.0

Size

In [9]:
df.groupby('Department').size()

Department
CS    2
IT    2
SE    1
dtype: int64

Filter Groups after Aggregation

In [10]:
df.groupby('Department').filter(lambda x: x['CGPA'].mean() > 3.5)

  Department Student  CGPA  Age
1         IT    Sara   3.8   22
3         IT   Usman   3.9   23
4         SE   Ahsan   3.6   21